// Generated by scripts/dm_json_gen.py — do not edit.
#pragma once
#include <string>
#include <string_view>
#include <utility>
#include <rtpmidid/dm_json/runtime.hpp>
#include "minimal.hpp"

namespace rtpmididns::dmjson {

void to_json(const ::rtpmididns::golden_foo_t &o, writer_t &w);
bool from_json(reader_t &r, ::rtpmididns::golden_foo_t &o) noexcept;
bool from_json(std::string_view sv, ::rtpmididns::golden_foo_t &o) noexcept;
inline std::string to_json(const ::rtpmididns::golden_foo_t &o) {
  writer_t w;
  to_json(o, w);
  std::string out;
  w.swap_into_string(out);
  return out;
}

} // namespace rtpmididns::dmjson
