Document: rtpmidid
Title: Debian rtpmidid Manual
Author: <insert document author here>
Abstract: This manual describes what rtpmidid is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rtpmidid/rtpmidid.sgml.gz

Format: postscript
Files: /usr/share/doc/rtpmidid/rtpmidid.ps.gz

Format: text
Files: /usr/share/doc/rtpmidid/rtpmidid.text.gz

Format: HTML
Index: /usr/share/doc/rtpmidid/html/index.html
Files: /usr/share/doc/rtpmidid/html/*.html
