FROM fedora:44

# Install build dependencies
RUN dnf install -y \
    rpm-build \
    cmake \
    ninja-build \
    gcc-c++ \
    avahi-devel \
    alsa-lib-devel \
    sqlite-devel \
    python3 \
    pandoc \
    git \
    systemd-rpm-macros \
    nodejs \
    npm \
    fmt-devel \
    && dnf clean all

# Create a non-root user for building
RUN useradd -m -s /bin/bash builder

# Copy build script
COPY ../build-rpm.sh /usr/local/bin/rtpmidid-build-rpm.sh
RUN chmod +x /usr/local/bin/rtpmidid-build-rpm.sh

WORKDIR /build
