// Autogenerated by scripts/json_dm_to_cpp.py — do not edit.
#include "control_commands_jsondm.hpp"
#include "control_status_jsondm.hpp"
#include "peer_status_jsondm.hpp"
#include <rtpmidid/jsondm.hpp>

namespace jsondm {
void jsondm::serializer<rtpmididns::remove_params_t>::write(
    const rtpmididns::remove_params_t &v, jsondm::Writer &w) {
  w.arr_begin();
  {
    jsondm::Writer::member_guard g(w, 0);
    jsondm::write(w, v.peer_id);
  }
  w.arr_end();
}
void jsondm::deserializer<rtpmididns::remove_params_t>::read(
    jsondm::Reader &r, rtpmididns::remove_params_t &v) {
  r.arr_begin();
  size_t i = 0;
  while (r.next_elem()) {
    jsondm::Reader::member_guard g(r, i);
    if (i == 0)
      jsondm::read(r, v.peer_id);
    else
      r.skip_value();
    ++i;
  }
  r.arr_end();
  if (i != 1)
    r.fail("1 array elements", FMT::format("{} elements", i));
}
void jsondm::serializer<rtpmididns::router_connect_params_t>::write(
    const rtpmididns::router_connect_params_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "from");
    jsondm::write(w, v.from);
  }
  {
    jsondm::Writer::member_guard g(w, "to");
    jsondm::write(w, v.to);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::router_connect_params_t>::read(
    jsondm::Reader &r, rtpmididns::router_connect_params_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "from") {
      jsondm::Reader::member_guard g(r, "from");
      jsondm::read(r, v.from);
    } else if (key == "to") {
      jsondm::Reader::member_guard g(r, "to");
      jsondm::read(r, v.to);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::connect_params_t>::write(
    const rtpmididns::connect_params_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "hostname");
    jsondm::write(w, v.hostname);
  }
  {
    jsondm::Writer::member_guard g(w, "port");
    jsondm::write(w, v.port);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::connect_params_t>::read(
    jsondm::Reader &r, rtpmididns::connect_params_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "hostname") {
      jsondm::Reader::member_guard g(r, "hostname");
      jsondm::read(r, v.hostname);
    } else if (key == "port") {
      jsondm::Reader::member_guard g(r, "port");
      jsondm::read(r, v.port);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::create_params_t>::write(
    const rtpmididns::create_params_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "type");
    jsondm::write(w, v.type);
  }
  if (v.name) {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, *v.name);
  }
  if (v.device) {
    jsondm::Writer::member_guard g(w, "device");
    jsondm::write(w, *v.device);
  }
  if (v.hostname) {
    jsondm::Writer::member_guard g(w, "hostname");
    jsondm::write(w, *v.hostname);
  }
  if (v.port) {
    jsondm::Writer::member_guard g(w, "port");
    jsondm::write(w, *v.port);
  }
  if (v.udp_port) {
    jsondm::Writer::member_guard g(w, "udp_port");
    jsondm::write(w, *v.udp_port);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::create_params_t>::read(
    jsondm::Reader &r, rtpmididns::create_params_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "type") {
      jsondm::Reader::member_guard g(r, "type");
      jsondm::read(r, v.type);
    } else if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "device") {
      jsondm::Reader::member_guard g(r, "device");
      jsondm::read(r, v.device);
    } else if (key == "hostname") {
      jsondm::Reader::member_guard g(r, "hostname");
      jsondm::read(r, v.hostname);
    } else if (key == "port") {
      jsondm::Reader::member_guard g(r, "port");
      jsondm::read(r, v.port);
    } else if (key == "udp_port") {
      jsondm::Reader::member_guard g(r, "udp_port");
      jsondm::read(r, v.udp_port);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::mdns_remove_params_t>::write(
    const rtpmididns::mdns_remove_params_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  if (v.hostname) {
    jsondm::Writer::member_guard g(w, "hostname");
    jsondm::write(w, *v.hostname);
  }
  {
    jsondm::Writer::member_guard g(w, "port");
    jsondm::write(w, v.port);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::mdns_remove_params_t>::read(
    jsondm::Reader &r, rtpmididns::mdns_remove_params_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "hostname") {
      jsondm::Reader::member_guard g(r, "hostname");
      jsondm::read(r, v.hostname);
    } else if (key == "port") {
      jsondm::Reader::member_guard g(r, "port");
      jsondm::read(r, v.port);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::export_rawmidi_params_t>::write(
    const rtpmididns::export_rawmidi_params_t &v, jsondm::Writer &w) {
  w.obj_begin();
  if (v.device) {
    jsondm::Writer::member_guard g(w, "device");
    jsondm::write(w, *v.device);
  }
  if (v.name) {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, *v.name);
  }
  if (v.local_udp_port) {
    jsondm::Writer::member_guard g(w, "local_udp_port");
    jsondm::write(w, *v.local_udp_port);
  }
  if (v.remote_udp_port) {
    jsondm::Writer::member_guard g(w, "remote_udp_port");
    jsondm::write(w, *v.remote_udp_port);
  }
  if (v.hostname) {
    jsondm::Writer::member_guard g(w, "hostname");
    jsondm::write(w, *v.hostname);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::export_rawmidi_params_t>::read(
    jsondm::Reader &r, rtpmididns::export_rawmidi_params_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "device") {
      jsondm::Reader::member_guard g(r, "device");
      jsondm::read(r, v.device);
    } else if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "local_udp_port") {
      jsondm::Reader::member_guard g(r, "local_udp_port");
      jsondm::read(r, v.local_udp_port);
    } else if (key == "remote_udp_port") {
      jsondm::Reader::member_guard g(r, "remote_udp_port");
      jsondm::read(r, v.remote_udp_port);
    } else if (key == "hostname") {
      jsondm::Reader::member_guard g(r, "hostname");
      jsondm::read(r, v.hostname);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::command_error_t>::write(
    const rtpmididns::command_error_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "error");
    jsondm::write(w, v.error);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::command_error_t>::read(
    jsondm::Reader &r, rtpmididns::command_error_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "error") {
      jsondm::Reader::member_guard g(r, "error");
      jsondm::read(r, v.error);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::export_help_t>::write(
    const rtpmididns::export_help_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "device");
    jsondm::write(w, v.device);
  }
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "local_udp_port");
    jsondm::write(w, v.local_udp_port);
  }
  {
    jsondm::Writer::member_guard g(w, "remote_udp_port");
    jsondm::write(w, v.remote_udp_port);
  }
  {
    jsondm::Writer::member_guard g(w, "hostname");
    jsondm::write(w, v.hostname);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::export_help_t>::read(
    jsondm::Reader &r, rtpmididns::export_help_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "device") {
      jsondm::Reader::member_guard g(r, "device");
      jsondm::read(r, v.device);
    } else if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "local_udp_port") {
      jsondm::Reader::member_guard g(r, "local_udp_port");
      jsondm::read(r, v.local_udp_port);
    } else if (key == "remote_udp_port") {
      jsondm::Reader::member_guard g(r, "remote_udp_port");
      jsondm::read(r, v.remote_udp_port);
    } else if (key == "hostname") {
      jsondm::Reader::member_guard g(r, "hostname");
      jsondm::read(r, v.hostname);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::export_error_t>::write(
    const rtpmididns::export_error_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "error");
    jsondm::write(w, v.error);
  }
  {
    jsondm::Writer::member_guard g(w, "params");
    jsondm::write(w, v.params);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::export_error_t>::read(
    jsondm::Reader &r, rtpmididns::export_error_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "error") {
      jsondm::Reader::member_guard g(r, "error");
      jsondm::read(r, v.error);
    } else if (key == "params") {
      jsondm::Reader::member_guard g(r, "params");
      jsondm::read(r, v.params);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::router_create_help_entry_t>::write(
    const rtpmididns::router_create_help_entry_t &v, jsondm::Writer &w) {
  w.obj_begin();
  if (v.name) {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, *v.name);
  }
  if (v.device) {
    jsondm::Writer::member_guard g(w, "device");
    jsondm::write(w, *v.device);
  }
  if (v.hostname) {
    jsondm::Writer::member_guard g(w, "hostname");
    jsondm::write(w, *v.hostname);
  }
  if (v.port) {
    jsondm::Writer::member_guard g(w, "port");
    jsondm::write(w, *v.port);
  }
  if (v.udp_port) {
    jsondm::Writer::member_guard g(w, "udp_port");
    jsondm::write(w, *v.udp_port);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::router_create_help_entry_t>::read(
    jsondm::Reader &r, rtpmididns::router_create_help_entry_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "device") {
      jsondm::Reader::member_guard g(r, "device");
      jsondm::read(r, v.device);
    } else if (key == "hostname") {
      jsondm::Reader::member_guard g(r, "hostname");
      jsondm::read(r, v.hostname);
    } else if (key == "port") {
      jsondm::Reader::member_guard g(r, "port");
      jsondm::read(r, v.port);
    } else if (key == "udp_port") {
      jsondm::Reader::member_guard g(r, "udp_port");
      jsondm::read(r, v.udp_port);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::router_create_help_t>::write(
    const rtpmididns::router_create_help_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "local_rawmidi_t");
    jsondm::write(w, v.local_rawmidi_t);
  }
  {
    jsondm::Writer::member_guard g(w, "network_rtpmidi_client_t");
    jsondm::write(w, v.network_rtpmidi_client_t);
  }
  {
    jsondm::Writer::member_guard g(w, "network_rtpmidi_listener_t");
    jsondm::write(w, v.network_rtpmidi_listener_t);
  }
  {
    jsondm::Writer::member_guard g(w, "local_alsa_peer_t");
    jsondm::write(w, v.local_alsa_peer_t);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::router_create_help_t>::read(
    jsondm::Reader &r, rtpmididns::router_create_help_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "local_rawmidi_t") {
      jsondm::Reader::member_guard g(r, "local_rawmidi_t");
      jsondm::read(r, v.local_rawmidi_t);
    } else if (key == "network_rtpmidi_client_t") {
      jsondm::Reader::member_guard g(r, "network_rtpmidi_client_t");
      jsondm::read(r, v.network_rtpmidi_client_t);
    } else if (key == "network_rtpmidi_listener_t") {
      jsondm::Reader::member_guard g(r, "network_rtpmidi_listener_t");
      jsondm::read(r, v.network_rtpmidi_listener_t);
    } else if (key == "local_alsa_peer_t") {
      jsondm::Reader::member_guard g(r, "local_alsa_peer_t");
      jsondm::read(r, v.local_alsa_peer_t);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::settings_projection_t>::write(
    const rtpmididns::settings_projection_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "alsa_name");
    jsondm::write(w, v.alsa_name);
  }
  {
    jsondm::Writer::member_guard g(w, "control_filename");
    jsondm::write(w, v.control_filename);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::settings_projection_t>::read(
    jsondm::Reader &r, rtpmididns::settings_projection_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "alsa_name") {
      jsondm::Reader::member_guard g(r, "alsa_name");
      jsondm::read(r, v.alsa_name);
    } else if (key == "control_filename") {
      jsondm::Reader::member_guard g(r, "control_filename");
      jsondm::read(r, v.control_filename);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::daemon_status_t>::write(
    const rtpmididns::daemon_status_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "version");
    jsondm::write(w, v.version);
  }
  {
    jsondm::Writer::member_guard g(w, "settings");
    jsondm::write(w, v.settings);
  }
  {
    jsondm::Writer::member_guard g(w, "router");
    jsondm::write(w, v.router);
  }
  {
    jsondm::Writer::member_guard g(w, "mdns");
    jsondm::write(w, v.mdns);
  }
  {
    jsondm::Writer::member_guard g(w, "exports");
    jsondm::write(w, v.exports);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::daemon_status_t>::read(
    jsondm::Reader &r, rtpmididns::daemon_status_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "version") {
      jsondm::Reader::member_guard g(r, "version");
      jsondm::read(r, v.version);
    } else if (key == "settings") {
      jsondm::Reader::member_guard g(r, "settings");
      jsondm::read(r, v.settings);
    } else if (key == "router") {
      jsondm::Reader::member_guard g(r, "router");
      jsondm::read(r, v.router);
    } else if (key == "mdns") {
      jsondm::Reader::member_guard g(r, "mdns");
      jsondm::read(r, v.mdns);
    } else if (key == "exports") {
      jsondm::Reader::member_guard g(r, "exports");
      jsondm::read(r, v.exports);
    } else
      r.skip_value();
  }
  r.obj_end();
}
} // namespace jsondm
