// Autogenerated by scripts/json_dm_to_cpp.py — do not edit.
#pragma once
#include "control_commands.hpp"
#include <rtpmidid/jsondm.hpp>

template <> struct jsondm::serializer<rtpmididns::remove_params_t> {
  static void write(const rtpmididns::remove_params_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::remove_params_t> {
  static void read(jsondm::Reader &, rtpmididns::remove_params_t &);
};
template <> struct jsondm::serializer<rtpmididns::router_connect_params_t> {
  static void write(const rtpmididns::router_connect_params_t &,
                    jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::router_connect_params_t> {
  static void read(jsondm::Reader &, rtpmididns::router_connect_params_t &);
};
template <> struct jsondm::serializer<rtpmididns::connect_params_t> {
  static void write(const rtpmididns::connect_params_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::connect_params_t> {
  static void read(jsondm::Reader &, rtpmididns::connect_params_t &);
};
template <> struct jsondm::serializer<rtpmididns::create_params_t> {
  static void write(const rtpmididns::create_params_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::create_params_t> {
  static void read(jsondm::Reader &, rtpmididns::create_params_t &);
};
template <> struct jsondm::serializer<rtpmididns::mdns_remove_params_t> {
  static void write(const rtpmididns::mdns_remove_params_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::mdns_remove_params_t> {
  static void read(jsondm::Reader &, rtpmididns::mdns_remove_params_t &);
};
template <> struct jsondm::serializer<rtpmididns::export_rawmidi_params_t> {
  static void write(const rtpmididns::export_rawmidi_params_t &,
                    jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::export_rawmidi_params_t> {
  static void read(jsondm::Reader &, rtpmididns::export_rawmidi_params_t &);
};
template <> struct jsondm::serializer<rtpmididns::command_error_t> {
  static void write(const rtpmididns::command_error_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::command_error_t> {
  static void read(jsondm::Reader &, rtpmididns::command_error_t &);
};
template <> struct jsondm::serializer<rtpmididns::export_help_t> {
  static void write(const rtpmididns::export_help_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::export_help_t> {
  static void read(jsondm::Reader &, rtpmididns::export_help_t &);
};
template <> struct jsondm::serializer<rtpmididns::export_error_t> {
  static void write(const rtpmididns::export_error_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::export_error_t> {
  static void read(jsondm::Reader &, rtpmididns::export_error_t &);
};
template <> struct jsondm::serializer<rtpmididns::router_create_help_entry_t> {
  static void write(const rtpmididns::router_create_help_entry_t &,
                    jsondm::Writer &);
};
template <>
struct jsondm::deserializer<rtpmididns::router_create_help_entry_t> {
  static void read(jsondm::Reader &, rtpmididns::router_create_help_entry_t &);
};
template <> struct jsondm::serializer<rtpmididns::router_create_help_t> {
  static void write(const rtpmididns::router_create_help_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::router_create_help_t> {
  static void read(jsondm::Reader &, rtpmididns::router_create_help_t &);
};
template <> struct jsondm::serializer<rtpmididns::settings_projection_t> {
  static void write(const rtpmididns::settings_projection_t &,
                    jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::settings_projection_t> {
  static void read(jsondm::Reader &, rtpmididns::settings_projection_t &);
};
template <> struct jsondm::serializer<rtpmididns::daemon_status_t> {
  static void write(const rtpmididns::daemon_status_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::daemon_status_t> {
  static void read(jsondm::Reader &, rtpmididns::daemon_status_t &);
};

template <>
struct FMT::formatter<rtpmididns::remove_params_t>
    : jsondm::formatter_base<rtpmididns::remove_params_t> {};
template <>
struct FMT::formatter<rtpmididns::router_connect_params_t>
    : jsondm::formatter_base<rtpmididns::router_connect_params_t> {};
template <>
struct FMT::formatter<rtpmididns::connect_params_t>
    : jsondm::formatter_base<rtpmididns::connect_params_t> {};
template <>
struct FMT::formatter<rtpmididns::create_params_t>
    : jsondm::formatter_base<rtpmididns::create_params_t> {};
template <>
struct FMT::formatter<rtpmididns::mdns_remove_params_t>
    : jsondm::formatter_base<rtpmididns::mdns_remove_params_t> {};
template <>
struct FMT::formatter<rtpmididns::export_rawmidi_params_t>
    : jsondm::formatter_base<rtpmididns::export_rawmidi_params_t> {};
template <>
struct FMT::formatter<rtpmididns::command_error_t>
    : jsondm::formatter_base<rtpmididns::command_error_t> {};
template <>
struct FMT::formatter<rtpmididns::export_help_t>
    : jsondm::formatter_base<rtpmididns::export_help_t> {};
template <>
struct FMT::formatter<rtpmididns::export_error_t>
    : jsondm::formatter_base<rtpmididns::export_error_t> {};
template <>
struct FMT::formatter<rtpmididns::router_create_help_entry_t>
    : jsondm::formatter_base<rtpmididns::router_create_help_entry_t> {};
template <>
struct FMT::formatter<rtpmididns::router_create_help_t>
    : jsondm::formatter_base<rtpmididns::router_create_help_t> {};
template <>
struct FMT::formatter<rtpmididns::settings_projection_t>
    : jsondm::formatter_base<rtpmididns::settings_projection_t> {};
template <>
struct FMT::formatter<rtpmididns::daemon_status_t>
    : jsondm::formatter_base<rtpmididns::daemon_status_t> {};
