/**
 * Real Time Protocol Music Instrument Digital Interface Daemon
 * Copyright (C) 2026 David Moreno Montero <dmoreno@coralbits.com>
 *
 * Control socket command payloads as /// [JSON-DM] decorated structs.
 * Serialization code is generated by scripts/json_dm_to_cpp.py
 * (control_commands_jsondm.hpp/.cpp) — do not edit the generated files.
 *
 * Wire shapes reproduce the legacy nlohmann protocol byte-compatibly; see
 * openspec/changes/add-json-dm/wire-inventory.md.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
#pragma once

#include "control_status.hpp"
#include "peer_status.hpp"
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace rtpmididns {

// router.remove params: positional array [peer_id].
/// [JSON-DM-ARRAY]
struct remove_params_t {
  uint32_t peer_id;
};

// router.connect / router.disconnect params: {from, to}.
/// [JSON-DM]
struct router_connect_params_t {
  uint32_t from;
  uint32_t to;
};

// connect params (object form; the array forms are handled by a hand-written
// reader at the boundary — see wire-inventory.md).
/// [JSON-DM]
struct connect_params_t {
  std::string name;
  std::string hostname;
  std::string port;
};

// router.create params: {type, <per-type fields>}.
/// [JSON-DM]
struct create_params_t {
  std::string type;
  std::optional<std::string> name;
  std::optional<std::string> device;
  std::optional<std::string> hostname;
  std::optional<std::variant<std::string, int>> port;
  std::optional<std::string> udp_port;
};

// mdns.remove params: {name, hostname (nullable), port}.
/// [JSON-DM]
struct mdns_remove_params_t {
  std::string name;
  std::optional<std::string> hostname;
  int port;
};

// export.rawmidi params: {device (required), <optional fields>}.
/// [JSON-DM]
struct export_rawmidi_params_t {
  std::optional<std::string> device;
  std::optional<std::string> name;
  std::optional<std::string> local_udp_port;
  std::optional<std::string> remote_udp_port;
  std::optional<std::string> hostname;
};

// Error result payload: {"error": "..."} (returned as a result by global
// commands, hoisted to the top level for peer commands — legacy behavior).
/// [JSON-DM]
struct command_error_t {
  std::string error;
};

// export.rawmidi help payload.
/// [JSON-DM]
struct export_help_t {
  std::string device;
  std::string name;
  std::string local_udp_port;
  std::string remote_udp_port;
  std::string hostname;
};
/// [JSON-DM]
struct export_error_t {
  std::string error;
  export_help_t params;
};

// router.create "list" help payload: per-type field descriptions.
/// [JSON-DM]
struct router_create_help_entry_t {
  std::optional<std::string> name;
  std::optional<std::string> device;
  std::optional<std::string> hostname;
  std::optional<std::string> port;
  std::optional<std::string> udp_port;
};
/// [JSON-DM]
struct router_create_help_t {
  router_create_help_entry_t local_rawmidi_t;
  router_create_help_entry_t network_rtpmidi_client_t;
  router_create_help_entry_t network_rtpmidi_listener_t;
  router_create_help_entry_t local_alsa_peer_t;
};

// status command result.
/// [JSON-DM]
struct settings_projection_t {
  std::string alsa_name;
  std::string control_filename;
};
/// [JSON-DM]
struct daemon_status_t {
  std::string version;
  settings_projection_t settings;
  std::vector<peer_status_variant_t> router;
  mdns_status_t mdns;
};

// Per-command result types (heterogeneous results are variants).
using create_result_t =
    std::variant<peer_status_variant_t, router_create_help_t, command_error_t>;
using connect_result_t =
    std::variant<std::vector<std::string>, command_error_t>;
using export_result_t = std::variant<std::vector<std::string>, export_error_t>;

} // namespace rtpmididns
