// Autogenerated by scripts/json_dm_to_cpp.py — do not edit.
#pragma once
#include "control_status.hpp"
#include <rtpmidid/jsondm.hpp>

template <> struct jsondm::serializer<rtpmididns::mdns_announcement_t> {
  static void write(const rtpmididns::mdns_announcement_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::mdns_announcement_t> {
  static void read(jsondm::Reader &, rtpmididns::mdns_announcement_t &);
};
template <> struct jsondm::serializer<rtpmididns::mdns_remote_announcement_t> {
  static void write(const rtpmididns::mdns_remote_announcement_t &,
                    jsondm::Writer &);
};
template <>
struct jsondm::deserializer<rtpmididns::mdns_remote_announcement_t> {
  static void read(jsondm::Reader &, rtpmididns::mdns_remote_announcement_t &);
};
template <> struct jsondm::serializer<rtpmididns::mdns_status_t> {
  static void write(const rtpmididns::mdns_status_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::mdns_status_t> {
  static void read(jsondm::Reader &, rtpmididns::mdns_status_t &);
};

template <>
struct FMT::formatter<rtpmididns::mdns_announcement_t>
    : jsondm::formatter_base<rtpmididns::mdns_announcement_t> {};
template <>
struct FMT::formatter<rtpmididns::mdns_remote_announcement_t>
    : jsondm::formatter_base<rtpmididns::mdns_remote_announcement_t> {};
template <>
struct FMT::formatter<rtpmididns::mdns_status_t>
    : jsondm::formatter_base<rtpmididns::mdns_status_t> {};
