// Autogenerated by scripts/json_dm_to_cpp.py — do not edit.
#include "control_status_jsondm.hpp"
#include <rtpmidid/jsondm.hpp>

namespace jsondm {
void jsondm::serializer<rtpmididns::mdns_announcement_t>::write(
    const rtpmididns::mdns_announcement_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "port");
    jsondm::write(w, v.port);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::mdns_announcement_t>::read(
    jsondm::Reader &r, rtpmididns::mdns_announcement_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "port") {
      jsondm::Reader::member_guard g(r, "port");
      jsondm::read(r, v.port);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::mdns_remote_announcement_t>::write(
    const rtpmididns::mdns_remote_announcement_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "hostname");
    jsondm::write(w, v.hostname);
  }
  {
    jsondm::Writer::member_guard g(w, "port");
    jsondm::write(w, v.port);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::mdns_remote_announcement_t>::read(
    jsondm::Reader &r, rtpmididns::mdns_remote_announcement_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "hostname") {
      jsondm::Reader::member_guard g(r, "hostname");
      jsondm::read(r, v.hostname);
    } else if (key == "port") {
      jsondm::Reader::member_guard g(r, "port");
      jsondm::read(r, v.port);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::mdns_status_t>::write(
    const rtpmididns::mdns_status_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "status");
    jsondm::write(w, v.status);
  }
  {
    jsondm::Writer::member_guard g(w, "announcements");
    jsondm::write(w, v.announcements);
  }
  {
    jsondm::Writer::member_guard g(w, "remote_announcements");
    jsondm::write(w, v.remote_announcements);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::mdns_status_t>::read(
    jsondm::Reader &r, rtpmididns::mdns_status_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "status") {
      jsondm::Reader::member_guard g(r, "status");
      jsondm::read(r, v.status);
    } else if (key == "announcements") {
      jsondm::Reader::member_guard g(r, "announcements");
      jsondm::read(r, v.announcements);
    } else if (key == "remote_announcements") {
      jsondm::Reader::member_guard g(r, "remote_announcements");
      jsondm::read(r, v.remote_announcements);
    } else
      r.skip_value();
  }
  r.obj_end();
}
} // namespace jsondm
