/**
 * Real Time Protocol Music Instrument Digital Interface Daemon
 * Copyright (C) 2026 David Moreno Montero <dmoreno@coralbits.com>
 *
 * Control socket status payloads as /// [JSON-DM] decorated structs.
 * Serialization code is generated by scripts/json_dm_to_cpp.py
 * (control_status_jsondm.hpp/.cpp) — do not edit the generated files.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace rtpmididns {

/// [JSON-DM]
struct mdns_announcement_t {
  std::string name;
  int port;
};

/// [JSON-DM]
struct mdns_remote_announcement_t {
  std::string name;
  std::string hostname;
  int port;
};

/// [JSON-DM]
struct mdns_status_t {
  std::string status;
  std::vector<mdns_announcement_t> announcements;
  std::vector<mdns_remote_announcement_t> remote_announcements;
};

} // namespace rtpmididns
