// Autogenerated by scripts/json_dm_to_cpp.py — do not edit.
#include "peer_status_jsondm.hpp"
#include <rtpmidid/jsondm.hpp>

namespace jsondm {
void jsondm::serializer<rtpmididns::peer_stats_t>::write(
    const rtpmididns::peer_stats_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "recv");
    jsondm::write(w, v.recv);
  }
  {
    jsondm::Writer::member_guard g(w, "sent");
    jsondm::write(w, v.sent);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::peer_stats_t>::read(
    jsondm::Reader &r, rtpmididns::peer_stats_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "recv") {
      jsondm::Reader::member_guard g(r, "recv");
      jsondm::read(r, v.recv);
    } else if (key == "sent") {
      jsondm::Reader::member_guard g(r, "sent");
      jsondm::read(r, v.sent);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::peer_latency_ms_t>::write(
    const rtpmididns::peer_latency_ms_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "last");
    jsondm::write(w, v.last);
  }
  {
    jsondm::Writer::member_guard g(w, "average");
    jsondm::write(w, v.average);
  }
  {
    jsondm::Writer::member_guard g(w, "stddev");
    jsondm::write(w, v.stddev);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::peer_latency_ms_t>::read(
    jsondm::Reader &r, rtpmididns::peer_latency_ms_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "last") {
      jsondm::Reader::member_guard g(r, "last");
      jsondm::read(r, v.last);
    } else if (key == "average") {
      jsondm::Reader::member_guard g(r, "average");
      jsondm::read(r, v.average);
    } else if (key == "stddev") {
      jsondm::Reader::member_guard g(r, "stddev");
      jsondm::read(r, v.stddev);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::peer_local_t>::write(
    const rtpmididns::peer_local_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "sequence_number");
    jsondm::write(w, v.sequence_number);
  }
  {
    jsondm::Writer::member_guard g(w, "sequence_number_ack");
    jsondm::write(w, v.sequence_number_ack);
  }
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "ssrc");
    jsondm::write(w, v.ssrc);
  }
  {
    jsondm::Writer::member_guard g(w, "port");
    jsondm::write(w, v.port);
  }
  {
    jsondm::Writer::member_guard g(w, "hostname");
    jsondm::write(w, v.hostname);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::peer_local_t>::read(
    jsondm::Reader &r, rtpmididns::peer_local_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "sequence_number") {
      jsondm::Reader::member_guard g(r, "sequence_number");
      jsondm::read(r, v.sequence_number);
    } else if (key == "sequence_number_ack") {
      jsondm::Reader::member_guard g(r, "sequence_number_ack");
      jsondm::read(r, v.sequence_number_ack);
    } else if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "ssrc") {
      jsondm::Reader::member_guard g(r, "ssrc");
      jsondm::read(r, v.ssrc);
    } else if (key == "port") {
      jsondm::Reader::member_guard g(r, "port");
      jsondm::read(r, v.port);
    } else if (key == "hostname") {
      jsondm::Reader::member_guard g(r, "hostname");
      jsondm::read(r, v.hostname);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::peer_remote_t>::write(
    const rtpmididns::peer_remote_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "sequence_number");
    jsondm::write(w, v.sequence_number);
  }
  {
    jsondm::Writer::member_guard g(w, "ssrc");
    jsondm::write(w, v.ssrc);
  }
  {
    jsondm::Writer::member_guard g(w, "port");
    jsondm::write(w, v.port);
  }
  {
    jsondm::Writer::member_guard g(w, "hostname");
    jsondm::write(w, v.hostname);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::peer_remote_t>::read(
    jsondm::Reader &r, rtpmididns::peer_remote_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "sequence_number") {
      jsondm::Reader::member_guard g(r, "sequence_number");
      jsondm::read(r, v.sequence_number);
    } else if (key == "ssrc") {
      jsondm::Reader::member_guard g(r, "ssrc");
      jsondm::read(r, v.ssrc);
    } else if (key == "port") {
      jsondm::Reader::member_guard g(r, "port");
      jsondm::read(r, v.port);
    } else if (key == "hostname") {
      jsondm::Reader::member_guard g(r, "hostname");
      jsondm::read(r, v.hostname);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::peer_rtp_detail_t>::write(
    const rtpmididns::peer_rtp_detail_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "latency_ms");
    jsondm::write(w, v.latency_ms);
  }
  {
    jsondm::Writer::member_guard g(w, "status");
    jsondm::write(w, v.status);
  }
  {
    jsondm::Writer::member_guard g(w, "local");
    jsondm::write(w, v.local);
  }
  {
    jsondm::Writer::member_guard g(w, "remote");
    jsondm::write(w, v.remote);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::peer_rtp_detail_t>::read(
    jsondm::Reader &r, rtpmididns::peer_rtp_detail_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "latency_ms") {
      jsondm::Reader::member_guard g(r, "latency_ms");
      jsondm::read(r, v.latency_ms);
    } else if (key == "status") {
      jsondm::Reader::member_guard g(r, "status");
      jsondm::read(r, v.status);
    } else if (key == "local") {
      jsondm::Reader::member_guard g(r, "local");
      jsondm::read(r, v.local);
    } else if (key == "remote") {
      jsondm::Reader::member_guard g(r, "remote");
      jsondm::read(r, v.remote);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::rtp_peer_status_t>::write(
    const rtpmididns::rtp_peer_status_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "peer");
    jsondm::write(w, v.peer);
  }
  {
    jsondm::Writer::member_guard g(w, "id");
    jsondm::write(w, v.id);
  }
  {
    jsondm::Writer::member_guard g(w, "send_to");
    jsondm::write(w, v.send_to);
  }
  {
    jsondm::Writer::member_guard g(w, "stats");
    jsondm::write(w, v.stats);
  }
  {
    jsondm::Writer::member_guard g(w, "type");
    jsondm::write(w, v.type);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::rtp_peer_status_t>::read(
    jsondm::Reader &r, rtpmididns::rtp_peer_status_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "peer") {
      jsondm::Reader::member_guard g(r, "peer");
      jsondm::read(r, v.peer);
    } else if (key == "id") {
      jsondm::Reader::member_guard g(r, "id");
      jsondm::read(r, v.id);
    } else if (key == "send_to") {
      jsondm::Reader::member_guard g(r, "send_to");
      jsondm::read(r, v.send_to);
    } else if (key == "stats") {
      jsondm::Reader::member_guard g(r, "stats");
      jsondm::read(r, v.stats);
    } else if (key == "type") {
      jsondm::Reader::member_guard g(r, "type");
      jsondm::read(r, v.type);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::alsa_peer_status_t>::write(
    const rtpmididns::alsa_peer_status_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "port");
    jsondm::write(w, v.port);
  }
  {
    jsondm::Writer::member_guard g(w, "id");
    jsondm::write(w, v.id);
  }
  {
    jsondm::Writer::member_guard g(w, "send_to");
    jsondm::write(w, v.send_to);
  }
  {
    jsondm::Writer::member_guard g(w, "stats");
    jsondm::write(w, v.stats);
  }
  {
    jsondm::Writer::member_guard g(w, "type");
    jsondm::write(w, v.type);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::alsa_peer_status_t>::read(
    jsondm::Reader &r, rtpmididns::alsa_peer_status_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "port") {
      jsondm::Reader::member_guard g(r, "port");
      jsondm::read(r, v.port);
    } else if (key == "id") {
      jsondm::Reader::member_guard g(r, "id");
      jsondm::read(r, v.id);
    } else if (key == "send_to") {
      jsondm::Reader::member_guard g(r, "send_to");
      jsondm::read(r, v.send_to);
    } else if (key == "stats") {
      jsondm::Reader::member_guard g(r, "stats");
      jsondm::read(r, v.stats);
    } else if (key == "type") {
      jsondm::Reader::member_guard g(r, "type");
      jsondm::read(r, v.type);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::rawmidi_peer_status_t>::write(
    const rtpmididns::rawmidi_peer_status_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "device");
    jsondm::write(w, v.device);
  }
  {
    jsondm::Writer::member_guard g(w, "status");
    jsondm::write(w, v.status);
  }
  {
    jsondm::Writer::member_guard g(w, "id");
    jsondm::write(w, v.id);
  }
  {
    jsondm::Writer::member_guard g(w, "send_to");
    jsondm::write(w, v.send_to);
  }
  {
    jsondm::Writer::member_guard g(w, "stats");
    jsondm::write(w, v.stats);
  }
  {
    jsondm::Writer::member_guard g(w, "type");
    jsondm::write(w, v.type);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::rawmidi_peer_status_t>::read(
    jsondm::Reader &r, rtpmididns::rawmidi_peer_status_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "device") {
      jsondm::Reader::member_guard g(r, "device");
      jsondm::read(r, v.device);
    } else if (key == "status") {
      jsondm::Reader::member_guard g(r, "status");
      jsondm::read(r, v.status);
    } else if (key == "id") {
      jsondm::Reader::member_guard g(r, "id");
      jsondm::read(r, v.id);
    } else if (key == "send_to") {
      jsondm::Reader::member_guard g(r, "send_to");
      jsondm::read(r, v.send_to);
    } else if (key == "stats") {
      jsondm::Reader::member_guard g(r, "stats");
      jsondm::read(r, v.stats);
    } else if (key == "type") {
      jsondm::Reader::member_guard g(r, "type");
      jsondm::read(r, v.type);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::listener_endpoint_t>::write(
    const rtpmididns::listener_endpoint_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "hostname");
    jsondm::write(w, v.hostname);
  }
  {
    jsondm::Writer::member_guard g(w, "port");
    jsondm::write(w, v.port);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::listener_endpoint_t>::read(
    jsondm::Reader &r, rtpmididns::listener_endpoint_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "hostname") {
      jsondm::Reader::member_guard g(r, "hostname");
      jsondm::read(r, v.hostname);
    } else if (key == "port") {
      jsondm::Reader::member_guard g(r, "port");
      jsondm::read(r, v.port);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::alsa_listener_status_t>::write(
    const rtpmididns::alsa_listener_status_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "endpoints");
    jsondm::write(w, v.endpoints);
  }
  {
    jsondm::Writer::member_guard g(w, "connection_count");
    jsondm::write(w, v.connection_count);
  }
  {
    jsondm::Writer::member_guard g(w, "status");
    jsondm::write(w, v.status);
  }
  {
    jsondm::Writer::member_guard g(w, "id");
    jsondm::write(w, v.id);
  }
  {
    jsondm::Writer::member_guard g(w, "send_to");
    jsondm::write(w, v.send_to);
  }
  {
    jsondm::Writer::member_guard g(w, "stats");
    jsondm::write(w, v.stats);
  }
  {
    jsondm::Writer::member_guard g(w, "type");
    jsondm::write(w, v.type);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::alsa_listener_status_t>::read(
    jsondm::Reader &r, rtpmididns::alsa_listener_status_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "endpoints") {
      jsondm::Reader::member_guard g(r, "endpoints");
      jsondm::read(r, v.endpoints);
    } else if (key == "connection_count") {
      jsondm::Reader::member_guard g(r, "connection_count");
      jsondm::read(r, v.connection_count);
    } else if (key == "status") {
      jsondm::Reader::member_guard g(r, "status");
      jsondm::read(r, v.status);
    } else if (key == "id") {
      jsondm::Reader::member_guard g(r, "id");
      jsondm::read(r, v.id);
    } else if (key == "send_to") {
      jsondm::Reader::member_guard g(r, "send_to");
      jsondm::read(r, v.send_to);
    } else if (key == "stats") {
      jsondm::Reader::member_guard g(r, "stats");
      jsondm::read(r, v.stats);
    } else if (key == "type") {
      jsondm::Reader::member_guard g(r, "type");
      jsondm::read(r, v.type);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::rtp_listener_status_t>::write(
    const rtpmididns::rtp_listener_status_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "port");
    jsondm::write(w, v.port);
  }
  {
    jsondm::Writer::member_guard g(w, "peers");
    jsondm::write(w, v.peers);
  }
  {
    jsondm::Writer::member_guard g(w, "id");
    jsondm::write(w, v.id);
  }
  {
    jsondm::Writer::member_guard g(w, "send_to");
    jsondm::write(w, v.send_to);
  }
  {
    jsondm::Writer::member_guard g(w, "stats");
    jsondm::write(w, v.stats);
  }
  {
    jsondm::Writer::member_guard g(w, "type");
    jsondm::write(w, v.type);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::rtp_listener_status_t>::read(
    jsondm::Reader &r, rtpmididns::rtp_listener_status_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "port") {
      jsondm::Reader::member_guard g(r, "port");
      jsondm::read(r, v.port);
    } else if (key == "peers") {
      jsondm::Reader::member_guard g(r, "peers");
      jsondm::read(r, v.peers);
    } else if (key == "id") {
      jsondm::Reader::member_guard g(r, "id");
      jsondm::read(r, v.id);
    } else if (key == "send_to") {
      jsondm::Reader::member_guard g(r, "send_to");
      jsondm::read(r, v.send_to);
    } else if (key == "stats") {
      jsondm::Reader::member_guard g(r, "stats");
      jsondm::read(r, v.stats);
    } else if (key == "type") {
      jsondm::Reader::member_guard g(r, "type");
      jsondm::read(r, v.type);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::rtp_listening_t>::write(
    const rtpmididns::rtp_listening_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "control_port");
    jsondm::write(w, v.control_port);
  }
  {
    jsondm::Writer::member_guard g(w, "midi_port");
    jsondm::write(w, v.midi_port);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::rtp_listening_t>::read(
    jsondm::Reader &r, rtpmididns::rtp_listening_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "control_port") {
      jsondm::Reader::member_guard g(r, "control_port");
      jsondm::read(r, v.control_port);
    } else if (key == "midi_port") {
      jsondm::Reader::member_guard g(r, "midi_port");
      jsondm::read(r, v.midi_port);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::rtp_multi_listener_status_t>::write(
    const rtpmididns::rtp_multi_listener_status_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "peers");
    jsondm::write(w, v.peers);
  }
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "listening");
    jsondm::write(w, v.listening);
  }
  {
    jsondm::Writer::member_guard g(w, "id");
    jsondm::write(w, v.id);
  }
  {
    jsondm::Writer::member_guard g(w, "send_to");
    jsondm::write(w, v.send_to);
  }
  {
    jsondm::Writer::member_guard g(w, "stats");
    jsondm::write(w, v.stats);
  }
  {
    jsondm::Writer::member_guard g(w, "type");
    jsondm::write(w, v.type);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::rtp_multi_listener_status_t>::read(
    jsondm::Reader &r, rtpmididns::rtp_multi_listener_status_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "peers") {
      jsondm::Reader::member_guard g(r, "peers");
      jsondm::read(r, v.peers);
    } else if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "listening") {
      jsondm::Reader::member_guard g(r, "listening");
      jsondm::read(r, v.listening);
    } else if (key == "id") {
      jsondm::Reader::member_guard g(r, "id");
      jsondm::read(r, v.id);
    } else if (key == "send_to") {
      jsondm::Reader::member_guard g(r, "send_to");
      jsondm::read(r, v.send_to);
    } else if (key == "stats") {
      jsondm::Reader::member_guard g(r, "stats");
      jsondm::read(r, v.stats);
    } else if (key == "type") {
      jsondm::Reader::member_guard g(r, "type");
      jsondm::read(r, v.type);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::alsa_connection_t>::write(
    const rtpmididns::alsa_connection_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "alsa");
    jsondm::write(w, v.alsa);
  }
  {
    jsondm::Writer::member_guard g(w, "local");
    jsondm::write(w, v.local);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::alsa_connection_t>::read(
    jsondm::Reader &r, rtpmididns::alsa_connection_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "alsa") {
      jsondm::Reader::member_guard g(r, "alsa");
      jsondm::read(r, v.alsa);
    } else if (key == "local") {
      jsondm::Reader::member_guard g(r, "local");
      jsondm::read(r, v.local);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::alsa_multi_listener_status_t>::write(
    const rtpmididns::alsa_multi_listener_status_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "connections");
    jsondm::write(w, v.connections);
  }
  {
    jsondm::Writer::member_guard g(w, "id");
    jsondm::write(w, v.id);
  }
  {
    jsondm::Writer::member_guard g(w, "send_to");
    jsondm::write(w, v.send_to);
  }
  {
    jsondm::Writer::member_guard g(w, "stats");
    jsondm::write(w, v.stats);
  }
  {
    jsondm::Writer::member_guard g(w, "type");
    jsondm::write(w, v.type);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::alsa_multi_listener_status_t>::read(
    jsondm::Reader &r, rtpmididns::alsa_multi_listener_status_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "connections") {
      jsondm::Reader::member_guard g(r, "connections");
      jsondm::read(r, v.connections);
    } else if (key == "id") {
      jsondm::Reader::member_guard g(r, "id");
      jsondm::read(r, v.id);
    } else if (key == "send_to") {
      jsondm::Reader::member_guard g(r, "send_to");
      jsondm::read(r, v.send_to);
    } else if (key == "stats") {
      jsondm::Reader::member_guard g(r, "stats");
      jsondm::read(r, v.stats);
    } else if (key == "type") {
      jsondm::Reader::member_guard g(r, "type");
      jsondm::read(r, v.type);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::peer_error_t>::write(
    const rtpmididns::peer_error_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "error");
    jsondm::write(w, v.error);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::peer_error_t>::read(
    jsondm::Reader &r, rtpmididns::peer_error_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "error") {
      jsondm::Reader::member_guard g(r, "error");
      jsondm::read(r, v.error);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::command_help_t>::write(
    const rtpmididns::command_help_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "name");
    jsondm::write(w, v.name);
  }
  {
    jsondm::Writer::member_guard g(w, "description");
    jsondm::write(w, v.description);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::command_help_t>::read(
    jsondm::Reader &r, rtpmididns::command_help_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "name") {
      jsondm::Reader::member_guard g(r, "name");
      jsondm::read(r, v.name);
    } else if (key == "description") {
      jsondm::Reader::member_guard g(r, "description");
      jsondm::read(r, v.description);
    } else
      r.skip_value();
  }
  r.obj_end();
}
void jsondm::serializer<rtpmididns::endpoint_params_t>::write(
    const rtpmididns::endpoint_params_t &v, jsondm::Writer &w) {
  w.obj_begin();
  {
    jsondm::Writer::member_guard g(w, "hostname");
    jsondm::write(w, v.hostname);
  }
  {
    jsondm::Writer::member_guard g(w, "port");
    jsondm::write(w, v.port);
  }
  w.obj_end();
}
void jsondm::deserializer<rtpmididns::endpoint_params_t>::read(
    jsondm::Reader &r, rtpmididns::endpoint_params_t &v) {
  r.obj_begin();
  while (r.next_key()) {
    auto key = r.key();
    if (key == "hostname") {
      jsondm::Reader::member_guard g(r, "hostname");
      jsondm::read(r, v.hostname);
    } else if (key == "port") {
      jsondm::Reader::member_guard g(r, "port");
      jsondm::read(r, v.port);
    } else
      r.skip_value();
  }
  r.obj_end();
}
} // namespace jsondm
