// Autogenerated by scripts/json_dm_to_cpp.py — do not edit.
#pragma once
#include "peer_status.hpp"
#include <rtpmidid/jsondm.hpp>

template <> struct jsondm::serializer<rtpmididns::peer_stats_t> {
  static void write(const rtpmididns::peer_stats_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::peer_stats_t> {
  static void read(jsondm::Reader &, rtpmididns::peer_stats_t &);
};
template <> struct jsondm::serializer<rtpmididns::peer_latency_ms_t> {
  static void write(const rtpmididns::peer_latency_ms_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::peer_latency_ms_t> {
  static void read(jsondm::Reader &, rtpmididns::peer_latency_ms_t &);
};
template <> struct jsondm::serializer<rtpmididns::peer_local_t> {
  static void write(const rtpmididns::peer_local_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::peer_local_t> {
  static void read(jsondm::Reader &, rtpmididns::peer_local_t &);
};
template <> struct jsondm::serializer<rtpmididns::peer_remote_t> {
  static void write(const rtpmididns::peer_remote_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::peer_remote_t> {
  static void read(jsondm::Reader &, rtpmididns::peer_remote_t &);
};
template <> struct jsondm::serializer<rtpmididns::peer_rtp_detail_t> {
  static void write(const rtpmididns::peer_rtp_detail_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::peer_rtp_detail_t> {
  static void read(jsondm::Reader &, rtpmididns::peer_rtp_detail_t &);
};
template <> struct jsondm::serializer<rtpmididns::rtp_peer_status_t> {
  static void write(const rtpmididns::rtp_peer_status_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::rtp_peer_status_t> {
  static void read(jsondm::Reader &, rtpmididns::rtp_peer_status_t &);
};
template <> struct jsondm::serializer<rtpmididns::alsa_peer_status_t> {
  static void write(const rtpmididns::alsa_peer_status_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::alsa_peer_status_t> {
  static void read(jsondm::Reader &, rtpmididns::alsa_peer_status_t &);
};
template <> struct jsondm::serializer<rtpmididns::rawmidi_peer_status_t> {
  static void write(const rtpmididns::rawmidi_peer_status_t &,
                    jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::rawmidi_peer_status_t> {
  static void read(jsondm::Reader &, rtpmididns::rawmidi_peer_status_t &);
};
template <> struct jsondm::serializer<rtpmididns::peer_error_t> {
  static void write(const rtpmididns::peer_error_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::peer_error_t> {
  static void read(jsondm::Reader &, rtpmididns::peer_error_t &);
};
template <> struct jsondm::serializer<rtpmididns::command_help_t> {
  static void write(const rtpmididns::command_help_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::command_help_t> {
  static void read(jsondm::Reader &, rtpmididns::command_help_t &);
};
template <> struct jsondm::serializer<rtpmididns::endpoint_params_t> {
  static void write(const rtpmididns::endpoint_params_t &, jsondm::Writer &);
};
template <> struct jsondm::deserializer<rtpmididns::endpoint_params_t> {
  static void read(jsondm::Reader &, rtpmididns::endpoint_params_t &);
};

template <>
struct FMT::formatter<rtpmididns::peer_stats_t>
    : jsondm::formatter_base<rtpmididns::peer_stats_t> {};
template <>
struct FMT::formatter<rtpmididns::peer_latency_ms_t>
    : jsondm::formatter_base<rtpmididns::peer_latency_ms_t> {};
template <>
struct FMT::formatter<rtpmididns::peer_local_t>
    : jsondm::formatter_base<rtpmididns::peer_local_t> {};
template <>
struct FMT::formatter<rtpmididns::peer_remote_t>
    : jsondm::formatter_base<rtpmididns::peer_remote_t> {};
template <>
struct FMT::formatter<rtpmididns::peer_rtp_detail_t>
    : jsondm::formatter_base<rtpmididns::peer_rtp_detail_t> {};
template <>
struct FMT::formatter<rtpmididns::rtp_peer_status_t>
    : jsondm::formatter_base<rtpmididns::rtp_peer_status_t> {};
template <>
struct FMT::formatter<rtpmididns::alsa_peer_status_t>
    : jsondm::formatter_base<rtpmididns::alsa_peer_status_t> {};
template <>
struct FMT::formatter<rtpmididns::rawmidi_peer_status_t>
    : jsondm::formatter_base<rtpmididns::rawmidi_peer_status_t> {};
template <>
struct FMT::formatter<rtpmididns::peer_error_t>
    : jsondm::formatter_base<rtpmididns::peer_error_t> {};
template <>
struct FMT::formatter<rtpmididns::command_help_t>
    : jsondm::formatter_base<rtpmididns::command_help_t> {};
template <>
struct FMT::formatter<rtpmididns::endpoint_params_t>
    : jsondm::formatter_base<rtpmididns::endpoint_params_t> {};
