/**
 * Real Time Protocol Music Instrument Digital Interface Daemon
 * Copyright (C) 2026 David Moreno Montero <dmoreno@coralbits.com>
 *
 * Typed peer status payloads for the midipeer interface.
 * Serialization code is generated by scripts/json_dm_to_cpp.py
 * (peer_status_jsondm.hpp/.cpp) — do not edit the generated files.
 *
 * Each per-peer-type status struct carries the router-assigned common
 * members (id, send_to, stats, type) after its own keys, reproducing the
 * legacy wire shapes; the router assigns the common members via a generic
 * std::visit.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
#pragma once

#include <cstdint>
#include <string>
#include <variant>
#include <vector>

namespace rtpmididns {

// Router-assigned statistics. Wire order: {recv, sent}.
/// [JSON-DM]
struct peer_stats_t {
  int recv;
  int sent;
};

// RTP peer detail (latency, status, local, remote).
/// [JSON-DM]
struct peer_latency_ms_t {
  double last;
  double average;
  double stddev;
};
/// [JSON-DM]
struct peer_local_t {
  uint16_t sequence_number;
  uint16_t sequence_number_ack;
  std::string name;
  uint32_t ssrc;
  int port;
  std::string hostname;
};
/// [JSON-DM]
struct peer_remote_t {
  std::string name;
  uint16_t sequence_number;
  uint32_t ssrc;
  int port;
  std::string hostname;
};
/// [JSON-DM]
struct peer_rtp_detail_t {
  peer_latency_ms_t latency_ms;
  std::string status;
  peer_local_t local;
  peer_remote_t remote;
};

// Per-peer-type status entries (own keys first, then router members).
/// [JSON-DM]
struct rtp_peer_status_t {
  std::string name;
  peer_rtp_detail_t peer;
  uint32_t id;
  std::vector<uint32_t> send_to;
  peer_stats_t stats;
  std::string type;
};
/// [JSON-DM]
struct alsa_peer_status_t {
  std::string name;
  int port;
  uint32_t id;
  std::vector<uint32_t> send_to;
  peer_stats_t stats;
  std::string type;
};
/// [JSON-DM]
struct rawmidi_peer_status_t {
  std::string name;
  std::string device;
  std::string status;
  uint32_t id;
  std::vector<uint32_t> send_to;
  peer_stats_t stats;
  std::string type;
};
// A peer whose status could not be produced: {"error": "<msg>"}.
/// [JSON-DM]
struct peer_error_t {
  std::string error;
};

// Command payloads shared by the peer interface.
// Help entry (array of these): {name, description}.
/// [JSON-DM]
struct command_help_t {
  std::string name;
  std::string description;
};
// Listener endpoint params: {hostname, port} where port may be a string
// or a number (legacy wire accepts both).
/// [JSON-DM]
struct endpoint_params_t {
  std::string hostname;
  std::variant<std::string, int> port;
};

using peer_status_variant_t =
    std::variant<rtp_peer_status_t, alsa_peer_status_t, rawmidi_peer_status_t,
                 peer_error_t>;

} // namespace rtpmididns
