// Autogenerated by scripts/json_dm_to_cpp.py — do not edit.
#include "settings_jsondm.hpp"
#include <rtpmidid/jsondm.hpp>

namespace jsondm {
void jsondm::ini_deserializer<rtpmididns::settings_t>::read(
    jsondm::IniReader &r, rtpmididns::settings_t &v) {
    r.for_each_run([&](std::string_view section,
                     const jsondm::IniReader::Section &sec) {
        if (section == "general") {
            sec.for_each([&](std::string_view key,
                             std::string_view value, size_t line) {
                if (key == "alsa_name") v.alsa_name = jsondm::ini::to_value<std::string>(value);
                else if (key == "alsa_network") v.alsa_network = jsondm::ini::to_value<bool>(value);
                else if (key == "control") v.control = jsondm::ini::to_value<std::string>(value);
                else if (key == "log_level") v.log_level = jsondm::ini::to_value<rtpmidid::logger_level_t>(value);
                else if (key == "rt_priority") v.rt_priority = jsondm::ini::to_value<int>(value);
                else throw jsondm::exception("{}:{}: Invalid key: {}", r.filename(), line, std::string(key));
            });
        }
        else if (section == "rtpmidi_announce") {
            rtpmididns::settings_t::rtpmidi_announce_t e;
            jsondm::ini_deserializer<rtpmididns::settings_t::rtpmidi_announce_t>::read(sec, e);
            v.rtpmidi_announce.push_back(std::move(e));
        }
        else if (section == "rtpmidi_discover") {
            jsondm::ini_deserializer<rtpmididns::settings_t::rtpmidi_discover_t>::read(sec, v.rtpmidi_discover);
        }
        else if (section == "alsa_announce") {
            rtpmididns::settings_t::alsa_announce_t e;
            jsondm::ini_deserializer<rtpmididns::settings_t::alsa_announce_t>::read(sec, e);
            v.alsa_announce.push_back(std::move(e));
        }
        else if (section == "connect_to") {
            rtpmididns::settings_t::connect_to_t e;
            jsondm::ini_deserializer<rtpmididns::settings_t::connect_to_t>::read(sec, e);
            v.connect_to.push_back(std::move(e));
        }
        else if (section == "alsa_hw_auto_export") {
            jsondm::ini_deserializer<rtpmididns::settings_t::alsa_hw_auto_export_t>::read(sec, v.alsa_hw_auto_export);
        }
        else if (section == "rawmidi") {
            rtpmididns::settings_t::rawmidi_t e;
            jsondm::ini_deserializer<rtpmididns::settings_t::rawmidi_t>::read(sec, e);
            v.rawmidi.push_back(std::move(e));
        }
        else throw jsondm::exception("{}:{}: Invalid section: {}", r.filename(), sec.line(), std::string(section));
    });
}
void jsondm::ini_serializer<rtpmididns::settings_t>::write(
    jsondm::IniWriter &w, const rtpmididns::settings_t &v) {
    w.section("general");
    w.key("alsa_name", jsondm::ini::to_text<std::string>(v.alsa_name));
    w.key("alsa_network", jsondm::ini::to_text<bool>(v.alsa_network));
    w.key("control", jsondm::ini::to_text<std::string>(v.control));
    w.key("log_level", jsondm::ini::to_text<rtpmidid::logger_level_t>(v.log_level));
    w.key("rt_priority", jsondm::ini::to_text<int>(v.rt_priority));
    for (const auto &e : v.rtpmidi_announce) {
        w.section("rtpmidi_announce");
        jsondm::ini_serializer<rtpmididns::settings_t::rtpmidi_announce_t>::write(w, e);
    }
    w.section("rtpmidi_discover");
    jsondm::ini_serializer<rtpmididns::settings_t::rtpmidi_discover_t>::write(w, v.rtpmidi_discover);
    for (const auto &e : v.alsa_announce) {
        w.section("alsa_announce");
        jsondm::ini_serializer<rtpmididns::settings_t::alsa_announce_t>::write(w, e);
    }
    for (const auto &e : v.connect_to) {
        w.section("connect_to");
        jsondm::ini_serializer<rtpmididns::settings_t::connect_to_t>::write(w, e);
    }
    w.section("alsa_hw_auto_export");
    jsondm::ini_serializer<rtpmididns::settings_t::alsa_hw_auto_export_t>::write(w, v.alsa_hw_auto_export);
    for (const auto &e : v.rawmidi) {
        w.section("rawmidi");
        jsondm::ini_serializer<rtpmididns::settings_t::rawmidi_t>::write(w, e);
    }
}
void jsondm::ini_deserializer<rtpmididns::settings_t::rtpmidi_announce_t>::read(
    const jsondm::IniReader::Section &sec, rtpmididns::settings_t::rtpmidi_announce_t &v) {
    sec.for_each([&](std::string_view key,
                     std::string_view value, size_t line) {
        if (key == "name") v.name = jsondm::ini::to_value<std::string>(value);
        else if (key == "port") v.port = jsondm::ini::to_value<std::string>(value);
        else throw jsondm::exception("{}:{}: Invalid key: {}", sec.filename(), line, std::string(key));
    });
}
void jsondm::ini_serializer<rtpmididns::settings_t::rtpmidi_announce_t>::write(
    jsondm::IniWriter &w, const rtpmididns::settings_t::rtpmidi_announce_t &v) {
    w.key("name", jsondm::ini::to_text<std::string>(v.name));
    w.key("port", jsondm::ini::to_text<std::string>(v.port));
}
void jsondm::ini_deserializer<rtpmididns::settings_t::rtpmidi_discover_t>::read(
    const jsondm::IniReader::Section &sec, rtpmididns::settings_t::rtpmidi_discover_t &v) {
    sec.for_each([&](std::string_view key,
                     std::string_view value, size_t line) {
        if (key == "enabled") v.enabled = jsondm::ini::to_value<bool>(value);
        else if (key == "name_positive_regex") v.name_positive_regex = jsondm::ini::to_value<std::regex>(value);
        else if (key == "name_negative_regex") v.name_negative_regex = jsondm::ini::to_value<std::regex>(value);
        else throw jsondm::exception("{}:{}: Invalid key: {}", sec.filename(), line, std::string(key));
    });
}
void jsondm::ini_serializer<rtpmididns::settings_t::rtpmidi_discover_t>::write(
    jsondm::IniWriter &w, const rtpmididns::settings_t::rtpmidi_discover_t &v) {
    w.key("enabled", jsondm::ini::to_text<bool>(v.enabled));
    w.key("name_positive_regex", jsondm::ini::to_text<std::regex>(v.name_positive_regex));
    w.key("name_negative_regex", jsondm::ini::to_text<std::regex>(v.name_negative_regex));
}
void jsondm::ini_deserializer<rtpmididns::settings_t::alsa_announce_t>::read(
    const jsondm::IniReader::Section &sec, rtpmididns::settings_t::alsa_announce_t &v) {
    sec.for_each([&](std::string_view key,
                     std::string_view value, size_t line) {
        if (key == "name") v.name = jsondm::ini::to_value<std::string>(value);
        else throw jsondm::exception("{}:{}: Invalid key: {}", sec.filename(), line, std::string(key));
    });
}
void jsondm::ini_serializer<rtpmididns::settings_t::alsa_announce_t>::write(
    jsondm::IniWriter &w, const rtpmididns::settings_t::alsa_announce_t &v) {
    w.key("name", jsondm::ini::to_text<std::string>(v.name));
}
void jsondm::ini_deserializer<rtpmididns::settings_t::connect_to_t>::read(
    const jsondm::IniReader::Section &sec, rtpmididns::settings_t::connect_to_t &v) {
    sec.for_each([&](std::string_view key,
                     std::string_view value, size_t line) {
        if (key == "hostname") v.hostname = jsondm::ini::to_value<std::string>(value);
        else if (key == "port") v.port = jsondm::ini::to_value<std::string>(value);
        else if (key == "name") v.name = jsondm::ini::to_value<std::string>(value);
        else if (key == "local_udp_port") v.local_udp_port = jsondm::ini::to_value<std::string>(value);
        else throw jsondm::exception("{}:{}: Invalid key: {}", sec.filename(), line, std::string(key));
    });
}
void jsondm::ini_serializer<rtpmididns::settings_t::connect_to_t>::write(
    jsondm::IniWriter &w, const rtpmididns::settings_t::connect_to_t &v) {
    w.key("hostname", jsondm::ini::to_text<std::string>(v.hostname));
    w.key("port", jsondm::ini::to_text<std::string>(v.port));
    w.key("name", jsondm::ini::to_text<std::string>(v.name));
    w.key("local_udp_port", jsondm::ini::to_text<std::string>(v.local_udp_port));
}
void jsondm::ini_deserializer<rtpmididns::settings_t::alsa_hw_auto_export_t>::read(
    const jsondm::IniReader::Section &sec, rtpmididns::settings_t::alsa_hw_auto_export_t &v) {
    sec.for_each([&](std::string_view key,
                     std::string_view value, size_t line) {
        if (key == "name_positive_regex") v.name_positive_regex = jsondm::ini::to_value<std::regex>(value);
        else if (key == "name_negative_regex") v.name_negative_regex = jsondm::ini::to_value<std::regex>(value);
        else if (key == "type") v.type = jsondm::ini::to_value<rtpmididns::settings_t::alsa_hw_auto_export_type_e>(value);
        else throw jsondm::exception("{}:{}: Invalid key: {}", sec.filename(), line, std::string(key));
    });
}
void jsondm::ini_serializer<rtpmididns::settings_t::alsa_hw_auto_export_t>::write(
    jsondm::IniWriter &w, const rtpmididns::settings_t::alsa_hw_auto_export_t &v) {
    if (v.name_positive_regex) w.key("name_positive_regex", jsondm::ini::to_text<std::regex>(*v.name_positive_regex));
    if (v.name_negative_regex) w.key("name_negative_regex", jsondm::ini::to_text<std::regex>(*v.name_negative_regex));
    w.key("type", jsondm::ini::to_text<rtpmididns::settings_t::alsa_hw_auto_export_type_e>(v.type));
}
void jsondm::ini_deserializer<rtpmididns::settings_t::rawmidi_t>::read(
    const jsondm::IniReader::Section &sec, rtpmididns::settings_t::rawmidi_t &v) {
    sec.for_each([&](std::string_view key,
                     std::string_view value, size_t line) {
        if (key == "device") v.device = jsondm::ini::to_value<std::string>(value);
        else if (key == "name") v.name = jsondm::ini::to_value<std::string>(value);
        else if (key == "local_udp_port") v.local_udp_port = jsondm::ini::to_value<std::string>(value);
        else if (key == "remote_udp_port") v.remote_udp_port = jsondm::ini::to_value<std::string>(value);
        else if (key == "hostname") v.hostname = jsondm::ini::to_value<std::string>(value);
        else throw jsondm::exception("{}:{}: Invalid key: {}", sec.filename(), line, std::string(key));
    });
}
void jsondm::ini_serializer<rtpmididns::settings_t::rawmidi_t>::write(
    jsondm::IniWriter &w, const rtpmididns::settings_t::rawmidi_t &v) {
    w.key("device", jsondm::ini::to_text<std::string>(v.device));
    w.key("name", jsondm::ini::to_text<std::string>(v.name));
    w.key("local_udp_port", jsondm::ini::to_text<std::string>(v.local_udp_port));
    w.key("remote_udp_port", jsondm::ini::to_text<std::string>(v.remote_udp_port));
    w.key("hostname", jsondm::ini::to_text<std::string>(v.hostname));
}
} // namespace jsondm
