// Autogenerated by scripts/json_dm_to_cpp.py — do not edit.
#pragma once
#include "settings.hpp"
#include <rtpmidid/jsondm.hpp>

template <> struct jsondm::ini_deserializer<rtpmididns::settings_t> {
  static void read(jsondm::IniReader &, rtpmididns::settings_t &);
};
template <> struct jsondm::ini_serializer<rtpmididns::settings_t> {
  static void write(jsondm::IniWriter &, const rtpmididns::settings_t &);
};
template <>
struct jsondm::ini_deserializer<rtpmididns::settings_t::rtpmidi_announce_t> {
  static void read(const jsondm::IniReader::Section &,
                   rtpmididns::settings_t::rtpmidi_announce_t &);
};
template <>
struct jsondm::ini_serializer<rtpmididns::settings_t::rtpmidi_announce_t> {
  static void write(jsondm::IniWriter &,
                    const rtpmididns::settings_t::rtpmidi_announce_t &);
};
template <>
struct jsondm::ini_deserializer<rtpmididns::settings_t::rtpmidi_discover_t> {
  static void read(const jsondm::IniReader::Section &,
                   rtpmididns::settings_t::rtpmidi_discover_t &);
};
template <>
struct jsondm::ini_serializer<rtpmididns::settings_t::rtpmidi_discover_t> {
  static void write(jsondm::IniWriter &,
                    const rtpmididns::settings_t::rtpmidi_discover_t &);
};
template <>
struct jsondm::ini_deserializer<rtpmididns::settings_t::alsa_announce_t> {
  static void read(const jsondm::IniReader::Section &,
                   rtpmididns::settings_t::alsa_announce_t &);
};
template <>
struct jsondm::ini_serializer<rtpmididns::settings_t::alsa_announce_t> {
  static void write(jsondm::IniWriter &,
                    const rtpmididns::settings_t::alsa_announce_t &);
};
template <>
struct jsondm::ini_deserializer<rtpmididns::settings_t::connect_to_t> {
  static void read(const jsondm::IniReader::Section &,
                   rtpmididns::settings_t::connect_to_t &);
};
template <>
struct jsondm::ini_serializer<rtpmididns::settings_t::connect_to_t> {
  static void write(jsondm::IniWriter &,
                    const rtpmididns::settings_t::connect_to_t &);
};
template <>
struct jsondm::ini_deserializer<rtpmididns::settings_t::alsa_hw_auto_export_t> {
  static void read(const jsondm::IniReader::Section &,
                   rtpmididns::settings_t::alsa_hw_auto_export_t &);
};
template <>
struct jsondm::ini_serializer<rtpmididns::settings_t::alsa_hw_auto_export_t> {
  static void write(jsondm::IniWriter &,
                    const rtpmididns::settings_t::alsa_hw_auto_export_t &);
};
template <> struct jsondm::ini_deserializer<rtpmididns::settings_t::rawmidi_t> {
  static void read(const jsondm::IniReader::Section &,
                   rtpmididns::settings_t::rawmidi_t &);
};
template <> struct jsondm::ini_serializer<rtpmididns::settings_t::rawmidi_t> {
  static void write(jsondm::IniWriter &,
                    const rtpmididns::settings_t::rawmidi_t &);
};
